### ISSUE TITLE
Crashes if published

### ISSUE THREAD

**Issue by Tesvia** [thomper/sweet-alert-dialog#1]
I'm using your fork (compile 'com.github.thomper:sweet-alert-dialog:v1.4.0')
It works on the emulator and works on the phones if installed when connecting them to Android Studio.
But, if I publish on the Play Store a beta release, it crashes.

**Comment by thomper** [comment]
That doesn't sound good.  I'd need more info to help, can you share the exception trace?  If you don't have access to it, see: https://stackoverflow.com/a/19968400

**Comment by Tesvia** [comment]
java.lang.RuntimeException: 	at com.ontbee.legacyforks.cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation(OptAnimationLoader.java)
  at <OR> com.ontbee.legacyforks.cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml (OptAnimationLoader.java)
  at com.ontbee.legacyforks.cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation (OptAnimationLoader.java)
  or                     .createAnimationFromXml (OptAnimationLoader.java)
  at com.ontbee.legacyforks.cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation (OptAnimationLoader.java)
  or                     .createAnimationFromXml (OptAnimationLoader.java)
  at com.ontbee.legacyforks.cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation (OptAnimationLoader.java)
  or                     .createAnimationFromXml (OptAnimationLoader.java)
  at com.ontbee.legacyforks.cn.pedant.SweetAlert.SweetAlertDialog.<init> (SweetAlertDialog.java)
  at com.areanovi.simpletimesheet.DayListActivity$2.onDismissedBySwipeRight (DayListActivity.java)
  at com.github.brnunes.swipeablerecyclerview.SwipeableRecyclerViewTouchListener$3.onAnimationEnd (SwipeableRecyclerViewTouchListener.java)
  at android.animation.ValueAnimator.endAnimation (ValueAnimator.java:1153)
  at android.animation.ValueAnimator.doAnimationFrame (ValueAnimator.java:1313)
  at android.animation.AnimationHandler.doAnimationFrame (AnimationHandler.java:146)
  at android.animation.AnimationHandler.-wrap2 (AnimationHandler.java)
  at android.animation.AnimationHandler$1.doFrame (AnimationHandler.java:54)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:928)
  at android.view.Choreographer.doCallbacks (Choreographer.java:705)
  at android.view.Choreographer.doFrame (Choreographer.java:637)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:916)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6823)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1557)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1445)

**Comment by yp25** [comment]
this solve my project

-keep class com.ontbee.legacyforks.cn.pedant.SweetAlert.** { *; }
-keep interface com.ontbee.legacyforks.cn.pedant.SweetAlert.** { *; }

please try this and give some comments @SixianOne . Thanks for this fork @thomper

**Comment by rohankandwal** [comment]
Got the same crash. In my case, I am using ProGuard

```
Fatal Exception: java.lang.RuntimeException: Unknown animation name: com.ontbee.legacyforks.cn.pedant.SweetAlert.Rotate3dAnimation error:com.ontbee.legacyforks.cn.pedant.SweetAlert.Rotate3dAnimation
       at com.ontbee.legacyforks.cn.pedant.SweetAlert.a.a(OptAnimationLoader.java:77)
       at com.ontbee.legacyforks.cn.pedant.SweetAlert.a.a(OptAnimationLoader.java:64)
       at com.ontbee.legacyforks.cn.pedant.SweetAlert.a.a(OptAnimationLoader.java:41)
       at com.ontbee.legacyforks.cn.pedant.SweetAlert.a.a(OptAnimationLoader.java:22)
       at com.ontbee.legacyforks.cn.pedant.SweetAlert.d.<init>(SweetAlertDialog.java:81)
       at com.example.b(BrowseHubMediaActivity.java:854)   
       at android.arch.lifecycle.LiveData.a(LiveData.java:109)
       at android.arch.lifecycle.LiveData.b(LiveData.java:126)
       at android.arch.lifecycle.LiveData.b(LiveData.java:282)
       at android.arch.lifecycle.p.b(MutableLiveData.java:33)
       at android.arch.lifecycle.v$1$1.a(Transformations.java:145)
       at android.arch.lifecycle.n$a.a(MediatorLiveData.java:152)
       at android.arch.lifecycle.LiveData.a(LiveData.java:109)
       at android.arch.lifecycle.LiveData.b(LiveData.java:126)
       at android.arch.lifecycle.LiveData.b(LiveData.java:282)
       at android.arch.lifecycle.p.b(MutableLiveData.java:33)
       at com.example
       at e.g$a$1$2.run(ExecutorCallAdapterFactory.java:79)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6205)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
```

**Comment by thomper** [comment]
This fork's not maintained, please use F0RIS' instead: https://github.com/F0RIS/sweet-alert-dialog
