### ISSUE TITLE
Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:null

### ISSUE THREAD

**Issue by VivekRai29** [thomper/sweet-alert-dialog#2]
Same issue :

java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:null
at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:77)
at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:64)
 at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:41)
at cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation(OptAnimationLoader.java:22)
 at cn.pedant.SweetAlert.SweetAlertDialog.<init>(SweetAlertDialog.java:80)

**Comment by RajeshNaddy** [comment]
Got the solution, the problem is with ProGuard rules..
What i did was downloaded the project, included library as module and added these rules in ProGuard..

`-keep class com.ontbee.legacyforks.cn.pedant.SweetAlert.** {*;}
-keepclassmembers  class com.ontbee.legacyforks.cn.pedant.SweetAlert.** {*;}`

Now it is perfectly working in signed APK

**Comment by thomper** [comment]
This fork's not maintained, please use F0RIS' instead: https://github.com/F0RIS/sweet-alert-dialog
